<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Audit Report Generated</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #6C63FF;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
        }
        .content {
            background-color: #f9f9f9;
            padding: 20px;
            margin: 20px 0;
        }
        .report-info {
            background-color: white;
            padding: 15px;
            margin: 10px 0;
            border-left: 4px solid #6C63FF;
        }
        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        .info-table td {
            padding: 8px;
            border-bottom: 1px solid #e0e0e0;
        }
        .info-table td:first-child {
            font-weight: bold;
            width: 40%;
            color: #555;
        }
        .footer {
            text-align: center;
            color: #777;
            font-size: 12px;
            padding: 20px;
            border-top: 2px solid #e0e0e0;
        }
        .highlight {
            background-color: #fff3cd;
            padding: 10px;
            border-left: 3px solid #ffc107;
            margin: 15px 0;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>📊 Audit Report Generated</h1>
    </div>

    <div class="content">
        <p>Hello {{ $user->first_name }},</p>

        <p>Your requested audit report has been generated and is attached to this email.</p>

        <div class="report-info">
            <h2>{{ $auditReport->name }}</h2>

            <table class="info-table">
                <tr>
                    <td>Report Type:</td>
                    <td>{{ $auditReport->type->label() }}</td>
                </tr>
                <tr>
                    <td>Period:</td>
                    <td>{{ $auditReport->from_date->format('M d, Y') }} - {{ $auditReport->to_date->format('M d, Y') }}</td>
                </tr>
                <tr>
                    <td>Generated By:</td>
                    <td>{{ $auditReport->generatedBy->first_name }} {{ $auditReport->generatedBy->last_name }}</td>
                </tr>
                <tr>
                    <td>Generated At:</td>
                    <td>{{ $auditReport->generated_at->format('M d, Y h:i A') }}</td>
                </tr>
            </table>
        </div>

        <div class="highlight">
            <strong>📎 Attachment:</strong> The complete audit report is attached as a PDF file.
        </div>

        <p>This report contains detailed activity logs for the specified period. Please review it carefully and keep it for your records.</p>

        <p style="font-size: 12px; color: #666; margin-top: 20px;">
            <strong>Note:</strong> Audit reports are generated for compliance and tracking purposes.
            If you notice any discrepancies, please contact your system administrator.
        </p>
    </div>

    <div class="footer">
        <p>This is an automated message from {{ config('app.name') }}</p>
        <p>&copy; {{ date('Y') }} VEGA ENTERPRISES. All rights reserved.</p>
    </div>
</div>
</body>
</html>
