<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report Generated</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background-color: #4F46E5; color: white; padding: 20px; text-align: center; }
        .content { background-color: #f9f9f9; padding: 20px; margin: 20px 0; }
        .report-info { background-color: white; padding: 15px; margin: 10px 0; border-left: 4px solid #4F46E5; }
        .button { background-color: #4F46E5; color: white; padding: 12px 24px; text-decoration: none; display: inline-block; margin: 10px 0; border-radius: 4px; }
        .footer { text-align: center; color: #777; font-size: 12px; padding: 20px; }
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>Report Generated</h1>
    </div>

    <div class="content">
        <p>Hello {{ $user->first_name }},</p>

        <p>Your requested report has been generated and is attached to this email.</p>

        <div class="report-info">
            <h2>{{ $reportName }}</h2>
            <p><strong>Generated by:</strong> {{ $generatedBy->first_name }} {{ $generatedBy->last_name }}</p>
            <p><strong>Generated at:</strong> {{ now()->format('M d, Y h:i A') }}</p>
        </div>

        <p>The report is attached as a PDF file. You can download it directly from this email.</p>
    </div>

    <div class="footer">
        <p>This is an automated message from {{ config('app.name') }}</p>
        <p>&copy; {{ date('Y') }} VEGA ENTERPRISES. All rights reserved.</p>
    </div>
</div>
</body>
</html>
