<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $data['report_name'] ?? 'Report' }}</title>

    <script src={{public_path("vendor/chart.umd.js")}}></script>
    <script src={{public_path("vendor/chart-plugin-annotation.min.js")}}></script>

    <style>
        @page { size: A4; margin: 10mm; }
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 8pt;
            color: #000;
            line-height: 1.4;
        }

        /* ── Header ── */
        .page-header {
            border-bottom: 0.5px solid #666;
            padding-bottom: 5px;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }
        .header-logo   { width: 50px; height: auto; }
        .header-center { text-align: center; flex: 1; }
        .header-title  { color: #003366; font-weight: bold; font-size: 11pt; margin-bottom: 2px; }
        .header-sub    { font-size: 8pt; }

        /* ── Footer ── */
        .page-footer {
            position: fixed;
            bottom: 0; left: 0; right: 0;
            border-top: 0.5px solid #666;
            padding: 5px 10mm;
            font-size: 7pt;
            background: white;
            display: flex;
            justify-content: space-between;
        }

        /* ── Sections ── */
        .section-title {
            color: #003366;
            font-weight: bold;
            font-size: 10pt;
            margin: 10px 0 5px;
            page-break-after: avoid;
        }
        .subsection-title {
            color: #003366;
            font-weight: bold;
            font-size: 9pt;
            margin: 8px 0 5px;
        }
        .divider { border-top: 0.5px solid #666; margin: 8px 0; }

        /* ── Info grid ── */
        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 5px 20px;
            margin-bottom: 8px;
        }
        .info-row { font-size: 8pt; line-height: 1.5; }
        .label    { font-weight: bold; }

        /* ── Chart ── */
        .chart-container {
            margin: 10px 0;
            page-break-inside: avoid;
            height: 280px;
        }
        .chart-container canvas { max-height: 280px !important; }

        /* ── Table ── */
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            table-layout: fixed;
        }
        table.data-table th {
            background-color: #003366;
            color: #fff;
            font-weight: bold;
            font-size: 7pt;
            padding: 4px;
            text-align: center;
            border: 0.5px solid #bebebe;
        }
        table.data-table td {
            font-size: 6pt;
            padding: 2px 4px;
            text-align: center;
            border: 0.5px solid #bebebe;
        }
        .val-critical { color: #ff0000; font-weight: bold; }
        .val-warning  { color: #ff8c00; font-weight: bold; }
        .val-normal   { color: #000; }

        @media print {
            .page-break           { page-break-before: always; }
            .no-break             { page-break-inside: avoid; }
        }
    </style>
</head>
<body>

{{-- ── Page Header ── --}}
<div class="page-header">
    <div style="width:50px">
        <img src="{{ public_path('vega-logo.png') }}" class="header-logo" alt="Logo">
    </div>
    <div class="header-center">
        <div class="header-title">Data Report</div>
        <div class="header-sub">{{ $data['report_name'] ?? 'Report' }}</div>
    </div>
    <div style="width:50px"></div>
</div>

{{-- ── Content ── --}}
@yield('content')

{{-- ── Page Footer ── --}}
<div class="page-footer">
    <div>
        <span class="label">Generated by:</span>
        <span style="color:#003366">{{ $data['user_name'] }}</span>
        &nbsp;@&nbsp;{{ now()->format('d-m-Y H:i:s') }}
        &nbsp;|&nbsp; This is a computer-generated report, no signature required ***
    </div>
    <div>Copyright © Vega™</div>
</div>

</body>
</html>
