<htmlpagefooter name="page-footer">
    <table width="100%" style="border-top: 0.5px solid #666666; padding-top: 5px; font-size: 8pt;">
        <tr>
            <td width="60%" style="vertical-align: top;">
                <div>
                    <span style="font-weight: normal;">Report Generated by: </span>
                    <span style="color: #003366; font-weight: normal;">{{ $data['user_name'] ?? 'System' }}</span>
                    <span style="font-weight: normal;"> @ {{ now()->format('d-m-Y H:i:s') }}</span>
                </div>
                <div style="margin-top: 3px;">
                    This is a computer-generated report, no signature is required ***
                </div>
            </td>
            <td width="40%" style="text-align: right; vertical-align: top;">
                <div>Page {PAGENO} of {nb}</div>
                <div style="margin-top: 3px;">Copyright © Vega™</div>
            </td>
        </tr>
    </table>
</htmlpagefooter>
