<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $report->name ?? 'Audit Report' }}</title>

    <style>
        @page {
            size: A4 landscape;
            margin: 10mm 10mm 10mm 10mm;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 8pt;
            color: #000;
            line-height: 1.4;
        }

        .page-header {
            border-bottom: 0.5px solid #666;
            padding-bottom: 5px;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .header-logo {
            width: 50px;
            height: auto;
        }

        .header-center {
            text-align: center;
            flex: 1;
        }

        .header-title {
            color: #003366;
            font-weight: bold;
            font-size: 11pt;
            margin-bottom: 2px;
        }

        .header-subtitle {
            font-size: 8pt;
            color: #000;
        }

        .page-footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            border-top: 0.5px solid #666;
            padding: 5px 10mm;
            font-size: 7pt;
            background: white;
            display: flex;
            justify-content: space-between;
        }

        .footer-left {
            flex: 1;
        }

        .footer-right {
            text-align: right;
        }

        .resource-info {
            margin-bottom: 15px;
        }

        .resource-info h3 {
            color: #003366;
            font-size: 10pt;
            margin: 0 0 10px 0;
        }

        .info-table {
            width: 100%;
            margin-bottom: 10px;
        }

        .info-table td {
            padding: 3px 0;
            font-size: 8.5pt;
        }

        .info-table td:nth-child(odd) {
            font-weight: bold;
            width: 20%;
        }

        .audit-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .audit-table th {
            background-color: #003366;
            color: #fff;
            padding: 8px;
            text-align: left;
            font-size: 8.5pt;
            font-weight: bold;
            border: 0.5px solid #bebebe;
        }

        .audit-table td {
            padding: 6px 8px;
            border: 0.5px solid #ccc;
            font-size: 8.5pt;
            word-wrap: break-word;
        }

        .audit-table th,
        .audit-table td {
            vertical-align: top;
        }

        .audit-table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        @media print {
            .page-break {
                page-break-before: always;
            }

            .no-break {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body>
<!-- Header -->
<div class="page-header">
    <div style="width: 50px;">
        @if(file_exists(public_path('vega-logo.png')))
            <img src="{{ public_path('vega-logo.png') }}" class="header-logo" alt="Logo">
        @endif
    </div>
    <div class="header-center">
        <div class="header-title">Audit Report</div>
        <div class="header-subtitle">{{ $report->name ?? 'Report' }}</div>
    </div>
    <div style="width: 50px;"></div>
</div>

<!-- Content -->
@yield('content')

<!-- Footer -->
<div class="page-footer">
    <div class="footer-left">
        <div>
            <span>Report Generated by: </span>
            <span style="color: #003366;">{{ $generated_by ?? 'System' }}</span>
            <span> @ {{ now()->format('d-m-Y H:i:s') }}</span>
        </div>
        <div style="margin-top: 3px;">
            This is a computer-generated report, no signature is required ***
        </div>
    </div>
    <div class="footer-right">
        <div>Copyright © Vega™</div>
    </div>
</div>
</body>
</html>
